### ISSUE TITLE
Is ruby-odpi going to replace ruby-oci8?

### ISSUE THREAD

**Issue by yahonda** [kubo/ruby-odpi#1]
I really appreciate `ruby-oci8` development. which makes Oracle enhanced adapter supports to connect to the latest versions of Oracle.

I have a question. In the long term, is `ruby-odpi` is going to replace `ruby-oci8`?

Well, "I do not know so far" or any answer is appreciated.

Thanks.

**Comment by cjbj** [comment]
@kubo - this is a question for you!

**Comment by kubo** [comment]
I'll continue to maintain ruby-oci8 because there are many legacy systems depending on Oracle versions not supported by odpi.
However ruby-odpi will be a replacement of ruby-oci8 for normal users using Oracle 11.2 or later.

Ruby-odpi will lack following ruby-oci8 features.

* Connection pooling
  This is not so-called connection pooling. It pools physical (TCP/IP) connections, not sessions.
  If this feature is implemented in ODPI-C, ruby-odpi will support it. But I have no will to request it to ODPI-C developers because I have not heard of ruby-oci8 users who use this.

* Metadata information using [OCIDescribeAny][]
  Oracle enhanced adapter and ruby-plsql use [OCI8#describe_table][] and [OCI8#describe_synonym][] respectively. However same information can be retrieved by accessing data dictionaries.
  (Ruby-plsql uses it for performance according to [this comment](https://github.com/rsim/ruby-plsql/blob/v0.6.0/lib/plsql/connection.rb#L182-L188).)

On the other hand, ruby-oci8 lacks many features which may be implemented in ruby-odpi in future.
(I'll try to implement all ODPI-C features to ruby-odpi.)
Some features may be ported from ruby-odpi to ruby-oci8 when I learn the features enough.

[OCIDescribeAny]: https://docs.oracle.com/database/122/LNOCI/describing-schema-metadata.htm
[OCI8#describe_table]: http://www.rubydoc.info/github/kubo/ruby-oci8/OCI8#describe_table-instance_method
[OCI8#describe_synonym]: http://www.rubydoc.info/github/kubo/ruby-oci8/OCI8#describe_synonym-instance_method

**Comment by yahonda** [comment]
Thanks for the reply and I agree with your direction.

I'd like to create a test branch to implement ruby-odpi version of Oracle enhanced adapter and ruby-plsql when ruby-odpi has minimum features to support 

* 11.2 or higher version
Oracle enhanced adapter can work with 10.2 or later but there is a plan to release the "nextval" version which will support 12.2 or higher.

* Connection pooling (TCP/IP connections pooling)
I did not know there is such a feature. and I do not think we need it.

* OCIDescribeAny
Happy to rewrite `OCIDescribeAny` code to dictionary queries like `all_synonyms`. This commit was 8 years old. Also it will help to reduce this code to be shared with JDBC ones also.

I'll keep monitoring this repository. Thanks again for your great work.
